In [13]:
import pandas as pd

In [14]:
df = pd.read_csv('Titanic-Dataset.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [15]:
#df.drop(DROP_COLS,axis=1,inplace=True)
DROP_COLS=["PassengerId","Name","Ticket"]
def drop_cols(df:pd.DataFrame,cols:list[str])->pd.DataFrame:
    return df.drop(columns=cols,inplace=True)

drop_cols(df,DROP_COLS)

In [16]:
dtype = df.dtypes
n_unique = df.nunique()
pd.DataFrame({"Dtyps ":dtype,"N_uniques ":n_unique}).T

           Survived Pclass  Sex      Age  SibSp  Parch     Fare Cabin Embarked
Dtyps         int64  int64  str  float64  int64  int64  float64   str      str
N_uniques         2      3    2       88      7      7      248   147        3

In [17]:
cols=['Survived','Pclass','Sex','SibSp','Parch','Embarked']
df[cols]=df[cols].astype("category")
pd.DataFrame(df.dtypes).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,category,category,category,float64,category,category,float64,str,category

In [21]:

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    category
 1   Pclass    891 non-null    category
 2   Sex       891 non-null    category
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    category
 5   Parch     891 non-null    category
 6   Fare      891 non-null    float64
 7   Cabin     204 non-null    str
 8   Embarked  889 non-null    category
dtypes: category(6), float64(2), str(1)
memory usage: 26.7 KB

In [23]:
null_values =df.isnull().sum()
ratio=(null_values/df.shape[0])*100
pd.DataFrame({"null ":null_values,"ratio ":ratio}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
null,0.0,0.0,0.0,177.00000,0.0,0.0,0.0,687.000000,2.000000
ratio,0.0,0.0,0.0,19.86532,0.0,0.0,0.0,77.104377,0.224467

In [25]:
df.dropna(subset=['Embarked'])
df.drop('Cabin', axis=1, inplace=True)

In [27]:
median =df['Age'].median()
df['Age']=df['Age'].fillna(median)

In [ ]:
num_cols = df.select_dtypes("number").columns
for col in num_cols:
    Q1=df[col].quantile(0.25)
    Q3=df[col].quantile(0.75)
    #print(Q1,Q3)
    IQR=Q3-Q1
    lower_fence = Q1 - 1.5*IQR
    lower_fence = Q3 + 1.5*IQR

    lower_outliers= df[df[col]<lower_fence][cols].values()
    upper_outliers= df[df[col]>upper_outliers][cols].values()

22.0 35.0
7.9104 31.0